[package]
name = "index_queue"
version = "0.1.0"
authors = ["Phil Ruffwind <rf@rufflewind.com>"]
documentation = "https://docs.rs/index_queue"
repository = "https://github.com/Rufflewind/index_queue"
license = "MIT/Apache-2.0"
exclude = [".gitignore", "README.md"]
